# The default Docker image
ARG IMAGE_BASE_NAME
ARG BASE_IMAGE_HASH
ARG BASE_BUILDER_IMAGE_HASH

# EDITED: use this build as image
FROM ${IMAGE_BASE_NAME}:base-builder-${BASE_BUILDER_IMAGE_HASH}
# copy files
COPY . /build/

# change working directory
WORKDIR /build

# install dependencies
# EDITED: add `poetry env use system` -> to use global python
# EDITED: add `poetry config virtualenvs.create false` -> to install deps into global package-list instead of virtualenv
RUN  pip install --no-cache-dir -U "pip==21.*" && \
  poetry env use system && \
  poetry config virtualenvs.create false && \
  poetry install --no-dev --no-root --no-interaction && \
  poetry build -f wheel -n && \
  pip install --no-deps dist/*.whl && \
  rm -rf dist *.egg-info

# set HOME environment variable
ENV HOME=/app

# update permissions & change user to not run as root
WORKDIR /app
RUN rm -rf /build


RUN chgrp -R 0 /app && chmod -R g=u /app && chmod o+wr /app
USER 1001

# create a volume for temporary data
VOLUME /tmp

# change shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# the entry point
EXPOSE 5005
ENTRYPOINT ["rasa"]
CMD ["--help"]
