# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
# recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# If you'd like to customize it, uncomment and adjust the pipeline.
# See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: WhitespaceTokenizer
    intent_tokenization_flag: True
    intent_split_symbol: "+"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 101
    learning_rate: 0.001
    batch_size: [64, 256]
    constrain_similarities: true
    embedding_dimension: 32
    dense_dimension:
      text: 128
      label: 32
    concat_dimension:
      text: 128
      label: 32
    number_of_transformer_layers: 2
    transformer_size: 256
    number_of_attention_heads: 4
    drop_rate: 0.2  # Dropout rate for encoder.
    drop_rate_attention: 0.0  # Dropout rate for attention.
  - name: EntitySynonymMapper
  # - name: ResponseSelector
  #   epochs: 100
  #   constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.2
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# No configuration for policies was provided. The following default policies were used to train your model.
# If you'd like to customize them, uncomment and adjust the policies.
# See https://rasa.com/docs/rasa/policies for more information.
  # - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.10
    core_fallback_action_name: "custom_action_fallback"
    enable_fallback_prediction: True
    restrict_rules: true
    check_for_contradictions: true
  - name: UnexpecTEDIntentPolicy
    tolerance: 0.12
    max_history: 3
    learning_rate: 2e-4
    epochs: 201
    constrain_similarities: true
    model_confidence: softmax  # softmax | linear_norm
    batch_size: [64, 256]
    connection_density: 0.89
    dense_dimension:
      text: 32
      action_text: 32
      label_action_text: 16
      intent: 16
      action_name: 16
      label_action_name: 16
      entities: 32
      slots: 64
      active_loop: 16
    concat_dimension:
      text: 32
      action_text: 32
      label_action_text: 32
    encoding_dimension: 16
    transformer_size:
      text: 128
      dialogue: 128
      action_text: 128
      label_action_text: 128
    number_of_transformer_layers:
      text: 1
      dialogue: 1
      action_text: 1
      label_action_text: 1
    number_of_attention_heads: 16
  - name: TEDPolicy
    max_history: 3
    learning_rate: 1e-4
    epochs: 2048
    constrain_similarities: true
    model_confidence: softmax
    batch_size: [128, 256]
    connection_density: 0.89
    dense_dimension:
      text: 32
      action_text: 32
      label_action_text: 16
      intent: 16
      action_name: 16
      label_action_name: 16
      entities: 32
      slots: 64
      active_loop: 16
    concat_dimension:
      text: 32
      action_text: 32
      label_action_text: 32
    encoding_dimension: 16
    transformer_size:
      text: 128
      dialogue: 128
      action_text: 128
      label_action_text: 128
    number_of_transformer_layers:
      text: 1
      dialogue: 1
      action_text: 1
      label_action_text: 1
    number_of_attention_heads: 16
